-- Medication AI Assistant
-- Supabase Database Schema
-- Team: Medication AI Assistant
-- Team Leader: Farooq Shahzad

-- =========================================
-- 1. USER PROFILES
-- =========================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    created_at timestamptz not null default now()
);

-- =========================================
-- 2. CHAT MESSAGES
-- =========================================

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null check (role in ('user', 'assistant')),
    content text not null,
    created_at timestamptz not null default now()
);

-- =========================================
-- 3. ENABLE ROW LEVEL SECURITY
-- =========================================

alter table public.profiles enable row level security;

alter table public.chat_messages enable row level security;

-- =========================================
-- 4. PROFILE SECURITY
-- =========================================

drop policy if exists "Users can view own profile"
on public.profiles;

create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);


drop policy if exists "Users can insert own profile"
on public.profiles;

create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);


drop policy if exists "Users can update own profile"
on public.profiles;

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- =========================================
-- 5. CHAT SECURITY
-- =========================================

drop policy if exists "Users can view own chat messages"
on public.chat_messages;

create policy "Users can view own chat messages"
on public.chat_messages
for select
to authenticated
using (auth.uid() = user_id);


drop policy if exists "Users can insert own chat messages"
on public.chat_messages;

create policy "Users can insert own chat messages"
on public.chat_messages
for insert
to authenticated
with check (auth.uid() = user_id);


drop policy if exists "Users can delete own chat messages"
on public.chat_messages;

create policy "Users can delete own chat messages"
on public.chat_messages
for delete
to authenticated
using (auth.uid() = user_id);

-- =========================================
-- 6. AUTOMATIC PROFILE CREATION
-- =========================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', '')
    );

    return new;
end;
$$;

drop trigger if exists on_auth_user_created
on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();
